#!/bin/bash
#
# Usage: psims -s <sitename> -p <paramfile> -c <campaign> -g <gridlist> [ -t test_result ] 

# crash: Report a problem and exit
crash() {
    echo "$@" >&2
    exit 1
}

# Usage: crash and report usage
usage() {
   crash "Usage: $0 -s <sitename> -p <paramfile> -c <campaign> -g <gridlist> [ -t test_result ]"
}

# Find absolute path
abspath() {
   readlink -f $1
}

# Verify an argument is not null
verify_not_null() {
   argname=$1; shift
   if [ _$1 != _ ]; then
      return 0;
   else
      echo Error: $argname undefined
      usage
   fi  
}

# Create a resume script
generate_resume() {
   resume_script=$1
   swift_script=$2
   rlog='$( ls -1t '$( basename $swift_script .swift )'*.rlog | head -1 )'
   site=$3
   shift 3
   echo "PATH=$PATH:$PWD/bin:$PWD/utils" >> $resume_script
   echo "source params.psims" >> $resume_script
   echo "swift -site $site -resume $rlog $swift_script $@ 2>&1 | tee -a swift.out" >> $resume_script
   echo "echo | tee -a swift.out" >> $resume_script
   chmod +x $resume_script
}

# Create a rerun script
generate_rerun() {
   rerun_script=$1
   swift_script=$2
   site=$3
   shift 3
   echo "PATH=$PATH:$PWD/bin:$PWD/utils" >> $rerun_script
   echo "source params.psims" >> $rerun_script
   echo "swift -site $site $swift_script $@ 2>&1 | tee -a swift.out" >> $rerun_script
   echo "echo | tee -a swift.out" >> $rerun_script
   chmod +x $rerun_script
}

# Process command line arguments
while [ $# -gt 0 ]; do
  case $1 in
    -c) campaign_arg=$2; shift 2;;
    -g) gridlist=$2; shift 2;;
    -p) paramfile=$2; shift 2;;
    -s) site=$2; shift 2;;
    -t) test_result=$2; shift 2;;
    *) usage;;
  esac
done

# Required arguments
verify_not_null campaign $campaign_arg
verify_not_null gridlist $gridlist
verify_not_null paramfile $paramfile
verify_not_null site $site

# Verify test result directory exists
if [ -n "$test_result" ]; then
   if [ ! -d "$test_result" ]; then
      crash "Unable to find test result directory $test_result"
   fi
fi

# Verify paramfile exists
paramfile=$( abspath $paramfile )
if [ ! -f $paramfile ]; then
   crash "Could not find parameter file $paramfile in params!"
fi

# Verify campaign directory exists
campaign_arg=$( abspath $campaign_arg )
if [ ! -d "$campaign_arg" ]; then
   crash "Campaign directory $campaign_arg does not exist!"
fi

# Verify gridlist exists
gridlist=$( abspath $gridlist )
if [ ! -f "$gridlist" ]; then
   crash "Gridlist file does not exist!"
fi

# Create next unique run id and run directory
export rundir=$( abspath $( echo run??? | sed -e 's/^.*run//' | awk '{ printf("run%03d\n", $1+1)}' ))
mkdir $rundir || crash "Unable to create run directory"
workdir=$rundir

sed -e '/^[[:space:]]*\(#.*\)*$/d' -e 's/#.*//' -e 's/  */=/' -e 's/^/export /' $paramfile > $rundir/params.psims
export PATH=$PWD/bin:$PWD/utils:$PATH
verify_params.sh $rundir/params.psims || crash "Aborting due to errors in params file"

# Verify Swift is in path
command -v swift >/dev/null 2>&1 || crash "Swift command is not available in PATH"

source $rundir/params.psims
export campaign=$campaign_arg # Ignore campaigns defined in params file
export SWIFT_HEAP_MAX=5120M
export SWIFT_USERHOME=$rundir

# Let 'midway' be an alias for midway and midway-long
if [ $site == "midway" ]; then
   site="midway,midway-long"
fi

# Check for work_directory location
if [ -n "$work_directory" ]; then
   workdir="$( abspath $work_directory )/$( basename $rundir )"
   if [ -d "$workdir" ]; then
      crash "Work directory $workdir already exists"
   fi
   mkdir -p $workdir
   cp $rundir/params.psims $workdir
fi

# Copy required files to the work_directory
cp $campaign/*.nc4 $workdir/
cp $gridlist $workdir/gridList.txt
cp RunpSIMS.swift $workdir
cp combine[1-3].swift $workdir
cp bin/RunpSIMS.sh $workdir
cp conf/swift.properties $workdir
cp $paramfile $workdir/paramfile
chmod a+rw $workdir/*

cd $workdir
source params.psims

# Record arguments in ABOUT file
cat << EOF > ABOUT
Site           = $site
Parameter      = $( abspath $paramfile )
Gridlist       = $( abspath $gridlist )
Campaign       = $campaign_arg
Run directory  = $rundir
Work directory = $workdir
EOF

# Echo parameters
cat ABOUT
echo -e "\nParameters:"
cat $workdir/params.psims
echo

# Extract input_tars
if [ -n "$tar_inputs" ]; then
   echo "Setting up data..."
   tar_files=$( echo $tar_inputs | sed s/,/' '/g )
   for file in $tar_files; do
      echo "Extracting $file"
      tar xvf $file 2>&1 | while read line; do
         x=$((x+1))
         echo -en "$x files extracted\r"
      done
   done
fi

# Extract s3_input_tars
if [ -n "$s3_tar_inputs" ]; then
   echo "Setting up data from s3..."
   s3_tar_files=$( echo $s3_tar_inputs | sed s/,/' '/g )
   for file in $s3_tar_files; do
      echo "Extracting $file"
      s3cmd get $file
      tar xvf $( basename $file ) 2>&1 | while read line; do
         x=$((x+1))
         echo -en "$x files extracted\r"
      done
   done
fi

# Assign default values for some values
num_chunks=${num_chunks:-1}
cal_vars=${cal_vars:-""} 
plots=${plots:-"true"}

# Create benchmark directory if needed
if [[ "$plots" == "true" ]]; then
   script_dirs="plots/scripts/RunpSIMS plots/scripts/combine1 plots/scripts/combine2 plots/scripts/combine3"
   mkdir -p $script_dirs
fi
arguments="-campaign=$campaign -workdir=$workdir -soils=$soils -variables=$variables -num_chunks=$num_chunks -pwd=$PWD -cal_vars=$cal_vars"

# Resume scripts
generate_resume resume.parts.sh RunpSIMS.swift $site $arguments
generate_resume resume.combine1.sh combine1.swift $site $arguments
generate_resume resume.combine2.sh combine2.swift $site $arguments
generate_resume resume.combine3.sh combine3.swift $site $arguments

# Rerun scripts
generate_rerun rerun.parts.sh RunpSIMS.swift $site $arguments
generate_rerun rerun.combine1.sh combine1.swift $site $arguments
generate_rerun rerun.combine2.sh combine2.swift $site $arguments
generate_rerun rerun.combine3.sh combine3.swift $site $arguments

# Run Swift scripts
./rerun.parts.sh
./rerun.combine1.sh
./rerun.combine2.sh
./rerun.combine3.sh

# Plots
if [[ "$plots" == "true" ]]; then
   echo Generating plots . . .  | tee -a swift.out
   echo | tee -a swift.out

   for script_dir in $script_dirs; do

      # Print time stats
      script_dir_base=$( basename $script_dir )
      echo "Execution times for script $script_dir_base" | tee -a swift.out
      ../utils/plotting_mean.py $script_dir | tee -a swift.out
      ../utils/plotting_swift.py $( ls -1t $rundir/${script_dir_base}*.log |head -1 ) | tee -a swift.out
      echo | tee -a swift.out

      # Generate plots
      for time_file in $( ls $script_dir/*.times 2>/dev/null ); do
         sort -n $time_file -o $time_file
         time_file=$time_file gnuplot ../utils/plot.gp 2>/dev/null
      done
   done

   echo -e "Done\n"
fi

# Testing
if [ -n "$test_result" ]; then
   echo Comparing results to test data at $test_result
   $rundir/../bin/cmp_output.py $rundir $test_result
   if [ "$?" == "0" ]; then
      echo "Test passed"
   else
      echo "Test failed"
   fi
fi

# Move data back to original run directory
if [ "$rundir" != "$workdir" ]; then
   echo Cleaning up data in $workdir...
   echo rm -rf $workdir/data
   echo Moving data from $workdir to $rundir...
   echo mv $workdir/* $rundir/
   echo rm -r $workdir
   echo Done
fi
